version: 2

models:
  - name: dim_location
    description: "Item"
    columns:
      - name: location_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: location_name
        description: "The item name"
